### PR TITLE
project of cash register

### PR DESCRIPTION
**Pull request by humuyar**
#: I make project of Cash Register.
#: I add a HTML file.
#: I add a CSS file for design my page.
#: I add a JavaScript file for some functionality of my page.
#: I add a linter config for handle the error.

### CODE REVIEW

**Comment by sodabarauf** [comment]
hi@humaira
Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!
bravo🥳
Status Approved 👍 Great Design Implemented
✔ Created a professional Repo (You created a repository with your project name)
✔ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔ Commit messages are meaningful
✔ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔ No linter errors (All linters checks have been passed 🟢)
✔ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔Your code is clean
✔Your repo has a professional README.md file
✔your project is responsive
✔your project is also deployed

**Comment by humuyar** [comment]
> hi@humaira Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!! bravo🥳 Status Approved 👍 Great Design Implemented ✔ Created a professional Repo (You created a repository with your project name) ✔ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch) ✔ Commit messages are meaningful ✔ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code) ✔ No linter errors (All linters checks have been passed 🟢) ✔ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review) ✔ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request) ✔Your code is clean ✔Your repo has a professional README.md file ✔your project is responsive ✔your project is also deployed

tnx sodaba jan from your feedback.

**Review by ahzamir — CHANGES_REQUESTED** [review]
Hey @humuyar 

- Well done you have done a great job by implementing lots of the requirements but still your project has some small issues please solve them and then mention me again here to provide you a re-review on your project:

- When the user enters a sufficient amount of cash for example price is 3 and the user enters 10 cash, it counts it and returns the change amount which your app is not doing this, and besides that it should show the amount of change in different cash values for the user according to the below [example](https://hamas2000.github.io/Build-a-Cash-Register/):
  - The issue with your app is that you did not show the total price and when user enters a sufficient amount of cash it shows the error message of `Status: INSUFFICIENT_FUNDS` instead it should return the `Status: Open` and show the amount of change the user gets from drawer in different chash values.

image

image

**Comment by humuyar** [comment]
@ahzamir 
sir i apply the feedback and also i change all design of my project bcuz when i do some changes to js file it didn't work

**Review by ahzamir — APPROVED** [review]
### Hi @humuyar 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Cash Register project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
